### ISSUE TITLE
Pimatic is not starting anymore after last updates

### ISSUE THREAD

**Issue by DDNRN** [pimatic/pimatic#521]
At the moment I have still the problem that pimatic is not starting. 
It won't restart after changes in config or after updates for example. 
Even from cmd line with ..restart or ..stop/start it hang up after some lines in logfile. Mostly its stopped with loading plugin-sunset. 
I think it's not a failure from a change in the config, there is no difference to the last running and i had the issue before already sometimes. 

See this log:
 
``` 
...
22:18:59.863 2015-02-04 Wednesday
22:19:11.035 [pimatic] info: Starting pimatic version 0.8.42
22:19:17.749 [pimatic] info: loading plugin: "pimatic-cron" (0.8.5)
22:19:20.244 [pimatic] info: loading plugin: "pimatic-mobile-frontend" (0.8.42)
22:19:25.816 [pimatic] info: loading plugin: "pimatic-shell-execute" (0.8.6)
22:19:25.991 [pimatic] info: loading plugin: "pimatic-gpio" (0.8.2)
22:19:26.401 [pimatic] info: loading plugin: "pimatic-sysinfo" (0.8.10)
22:19:27.028 [pimatic] info: loading plugin: "pimatic-ping" (0.8.3)
22:19:27.286 [pimatic] info: loading plugin: "pimatic-sunrise" (0.8.0)
22:26:59.012 2015-02-04 Wednesday
22:27:10.165 [pimatic] info: Starting pimatic version 0.8.42
22:27:16.299 [pimatic] info: loading plugin: "pimatic-cron" (0.8.5)
22:27:18.608 [pimatic] info: loading plugin: "pimatic-mobile-frontend" (0.8.42)
22:27:23.301 [pimatic] info: loading plugin: "pimatic-shell-execute" (0.8.6)
22:27:23.480 [pimatic] info: loading plugin: "pimatic-gpio" (0.8.2)
22:27:23.890 [pimatic] info: loading plugin: "pimatic-sysinfo" (0.8.10)
22:27:24.507 [pimatic] info: loading plugin: "pimatic-ping" (0.8.3)
22:27:24.757 [pimatic] info: loading plugin: "pimatic-sunrise" (0.8.0)
22:37:57.304 2015-02-04 Wednesday
22:38:09.865 [pimatic] info: Starting pimatic version 0.8.42
22:38:16.354 [pimatic] info: loading plugin: "pimatic-cron" (0.8.5)
22:38:18.865 [pimatic] info: loading plugin: "pimatic-mobile-frontend" (0.8.42)
22:38:24.412 [pimatic] info: loading plugin: "pimatic-shell-execute" (0.8.6)
22:38:24.617 [pimatic] info: loading plugin: "pimatic-gpio" (0.8.2)
22:38:25.141 [pimatic] info: loading plugin: "pimatic-sysinfo" (0.8.10)
22:38:25.713 [pimatic] info: loading plugin: "pimatic-ping" (0.8.3)
22:38:26.015 [pimatic] info: loading plugin: "pimatic-sunrise" (0.8.0)
````

I got this already some days before, run off after switch off power from RasPi and start again, but not this time. 

Is there any other point to take a look for or get info about whats wrong?

**Comment by DDNRN** [comment]
It should have been the plugin-weather whitch is the next after sunrise.
After i delete this i could restart, veryfied it several times. activated = no start of pimatic.  
Strange is why this makes trouble without any change from my side on that plugin in the last days?

**Comment by jensebub** [comment]
I've got the same issue,...
first i thougt the same, it could be an "device" or a "plugin", but testing Points out, that 
if i use my config.json without any rules, starting is ok,... just as i use rules with an arduino-switch it hangs up at reboot with an segfault,... (which is vissible at servermode-start, not daemonizing)
that issue began with the last updates,...

**Comment by incmve** [comment]
I had the same problem but after restarting it again I had no issue any more

**Comment by jensebub** [comment]
there's no correlation with restarting,... i tried 4 hours yesterday,... sometimes it works, sometimes not,...
without any rule, but with all plugins and devices it restarts without issue , everytime!

**Comment by kjdijkema** [comment]
I am experiencing similar problems after updating to the newest version of pimatic

**Comment by sweetpi** [comment]
I will have a closer look at this. Do you all get the segfault message if you start pimatic not as service `node_modules/pimatic/pimatic.js`?

I don't think that it is the weather plugin, but its hard to debug without knowing where it hangs.

**Comment by jensebub** [comment]
I think so, too. there is no correlation between the weather-plugin and the segfault. I've tried a lot.
I can submit you my config.json if you think it's easier to debug...
There are at least 2000 rows...

**Comment by incmve** [comment]
There is no correlation with the size of the config, my config only had a few items.
Weather plugin is not the issue, I don't have it installed.

**Comment by DDNRN** [comment]
crazy! 
Today it starts without a problem again with activated weather plugin.
I tried without deamon, but everything is fine, there is no err-message, exept no data connection from weather plugin. 

Yesterday I wasn't able to get it run while the plugin was activated, without it even crashed 2 times at later evening. Through the night and today it was running without issues, and now as I told before, even with same config like last days it is running.  

But the weather plugin is still not working! There are no actual weather data. 
````
17:51:09.255 [pimatic] new device "Mode"...
17:51:09.384 [pimatic] new device "Set Temperature"...
17:51:09.510 [pimatic] new device "Set Mode"...
17:51:09.924 [pimatic] new device "Wetter aktuell Weeze"...
17:51:24.937 [pimatic] rule test: set $temperature to 8
17:51:25.662 [pimatic-homeduino] Connected to homeduino device.
17:51:26.568 [pimatic-mobile-frontend] packing static assets
17:51:28.590 [pimatic-mobile-frontend] packing static assets finished
17:51:28.624 [pimatic-mobile-frontend] rendering html
17:51:53.114 [pimatic-mobile-frontend] rendering html finished
17:51:53.256 [pimatic] listening for http-request on port 8081...
17:51:53.415 [pimatic-weather] ETIMEDOUT
17:51:53.440 [pimatic] Could not get attribute value of Wetter aktuell Weeze.status: ETIMEDOUT
17:51:53.452 [pimatic] Could not get attribute value of Wetter aktuell Weeze.windspeed: ETIMEDOUT
17:51:53.464 [pimatic] Could not get attribute value of Wetter aktuell Weeze.temperature: ETIMEDOUT
17:51:53.475 [pimatic] Could not get attribute value of Wetter aktuell Weeze.humidity: ETIMEDOUT
17:51:53.489 [pimatic] Could not update variable weather.status: ETIMEDOUT
17:51:53.502 [pimatic] Could not update variable weather.windspeed: ETIMEDOUT
17:51:53.513 [pimatic] Could not update variable weather.temperature: ETIMEDOUT
17:51:53.524 [pimatic] Could not update variable weather.humidity: ETIMEDOUT
````

**Comment by DDNRN** [comment]
>> But the weather plugin is still not working! There are no actual weather data. 
After about 1 hour the weather data is back again!

**Comment by sweetpi** [comment]
Ok some results, I can reproduce the crash with the error "TypeError: Cannot read property 'length' of undefined"

But no segfault or so. 
@DDNRN, @jensebub, @kjdijkema, @incmve 

1. Do you get an error? 
2. If yes what does it say? 

If its not the error mentioned above it would be great if you could post or email me the following info:

*  Output of `node --version`
*  Output of  `cd pimatic-app` and `npm list`
*  Output of `cd pimatic-app` and `ls -alh`
* If you like your config, I think that would help me to trace down the problem.

**Comment by kjdijkema** [comment]
I get the following error:
```
 [pimatic-homeduino] Couldn't connect (operation timed out after 20000 ms), retrying...
TypeError: Cannot read property 'length' of undefined
    at Function.Buffer.concat (buffer.js:491:20)
    at afterRead (/home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:323:36)
    at /home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/serialport.js:342:9
    at Object.wrapper [as oncomplete] (fs.js:454:17)
```
Furthermore:
I can only start pimatic with this command:
```
sudo pimatic-app/node_modules/pimatic/pimatic.js
```
Using the command
```
sudo pimatic.js start
```
results in a dead pidfile, no debug output.

Output of node --version: v0.10.24
Output of cd pimatic-app and npm list is very long, but ends with:
```
npm ERR! extraneous: q@1.0.1 /home/pi/pimatic-app/node_modules/pimatic/node_modules/decl-api/node_modules/q
npm ERR! not ok code 0
```
Output of ls -alh:
```
total 41M
drwxr-xr-x   6 pi   pi   4.0K Feb  7 10:53 .
drwxr-xr-x  10 pi   pi   4.0K Jan  5 20:46 ..
-rwxrw-rw-   1 pi   pi    19K Feb  7 10:52 config.json
drwxrwxrwx   3 root root 4.0K Dec  3 21:48 .node-gyp
drwxr-xr-x  16 pi   pi   4.0K Feb  4 21:10 node_modules
drwxrwxrwx 109 pi   pi    12K Feb  4 21:17 .npm
-rw-rw-rw-   1 root root 395K Feb  7 10:55 pimatic-daemon.log
-rw-r--r--   1 root root  40M Feb  7 10:52 pimatic-database.sqlite
-rw-r--r--   1 root root    0 Feb  7 10:53 pimatic-database.sqlite-wal
-rw-rw-rw-   1 root root    4 Feb  7 10:53 pimatic.pid
drwxrwxrwx   3 root root 4.0K Feb  4 21:18 tmp
```

I don't have your e-mail address so I can't mail my config...

**Comment by sweetpi** [comment]
@kjdijkema Thanks, this one is that one I can reproduce and fix. You can find my email [at the end of the README](https://github.com/pimatic/pimatic#copyright--license)

But I don't need your config, because I think I already did find the reason for that. But didn't find a nice way to fix it yet.

**Comment by sweetpi** [comment]
I've published pimatic v0.8.43 which sould solve the problem mentioned above. I'm happy about feedback.

**Comment by Yves911** [comment]
@sweetpi i still get frequent crash. Sometimes pimatic will segfault at the init phase (loading plugins, or discovering devices). Most of the time it will segfault during communication with homeduino...
For example:
tail -f pimatic-daemon.log
```
16:56:15.857 [pimatic] info: loading plugin: "pimatic-links" (0.8.5)
16:56:15.988 [pimatic] info: loading plugin: "pimatic-homeduino" (0.8.36)
16:56:16.889 [pimatic] info: loading plugin: "pimatic-mail" (0.8.2)
16:56:18.579 [pimatic] info: loading plugin: "pimatic-log-reader" (0.8.2)
16:56:18.780 [pimatic] info: loading plugin: "pimatic-cron" (0.8.5)
16:56:19.204 [pimatic] info: loading plugin: "pimatic-mobile-frontend" (0.8.40)
16:56:22.069 [pimatic] info: loading plugin: "pimatic-shell-execute" (0.8.5)
16:56:22.168 [pimatic] info: loading plugin: "pimatic-filebrowser" (0.8.0)
16:56:22.248 [pimatic] warn: package.json of "pimatic-filebrowser" has no "configSchema" property. Could not validate config.
16:56:22.254 [pimatic] info: loading plugin: "pimatic-pushbullet" (0.8.4)
```
and nothing more pimatic process crashed...
right after that i try to start pimatic again, this time it's ok.
strange...

**Comment by sweetpi** [comment]
Hm that's the problem, that I can not get the segfault. I just got the buffer error. :(

**Comment by jensebub** [comment]
it's here the same.
tail -f pimatic-daemon.log:
crashed without nothing,...
```
16:48:36.220 2015-02-07 Saturday
16:48:40.414 [pimatic] info: Starting pimatic version 0.8.43
16:48:43.074 [pimatic] info: loading plugin: "pimatic-cron" (0.8.5)
16:48:43.785 [pimatic] info: loading plugin: "pimatic-mobile-frontend" (0.8.42)
16:48:45.453 [pimatic] info: loading plugin: "pimatic-gpio" (0.8.2)
16:48:45.642 [pimatic] info: loading plugin: "pimatic-lcd" (0.8.2)
16:48:46.523 [pimatic] info: loading plugin: "pimatic-athome" (0.8.2)
16:48:46.947 [pimatic] info: loading plugin: "pimatic-ping" (0.8.3)
16:48:47.023 [pimatic] info: loading plugin: "pimatic-homeduino" (0.8.36)
16:48:47.584 [pimatic] info: loading plugin: "pimatic-mail" (0.8.2)
16:48:48.308 [pimatic] info: loading plugin: "pimatic-log-reader" (0.8.2)
16:48:48.375 [pimatic] info: loading plugin: "pimatic-shell-execute" (0.8.6)
16:48:48.427 [pimatic] info: loading plugin: "pimatic-sunrise" (0.8.0)
16:48:48.489 [pimatic] info: loading plugin: "pimatic-weather" (0.8.11)
16:48:50.244 [pimatic] info: loading plugin: "pimatic-sysinfo" (0.8.10)
16:48:50.461 [pimatic] info: loading plugin: "pimatic-max" (0.8.9)
16:48:50.584 [pimatic] info: loading plugin: "pimatic-links" (0.8.5)
```
another start not as a service:
```
17:06:30.102 [pimatic-mobile-frontend] rendering theme: graphite/water
17:06:33.741 [pimatic-mobile-frontend] rendering theme finished
17:08:24.349 [pimatic-mobile-frontend] rendering theme: graphite/dark
17:08:27.951 [pimatic-mobile-frontend] rendering theme finished
[1]    23080 segmentation fault (core dumped)  node_modules/pimatic/pimatic.js
```

**Comment by sweetpi** [comment]
@jensebub Could you please post the following?

*  Output of `node --version`
*  Output of  `cd pimatic-app` and `npm list`
*  Output of `cd pimatic-app` and `ls -alh`
* If you like your config, I think that would help me to trace down the problem.

**Comment by sweetpi** [comment]
> [1]    23080 segmentation fault (core dumped)  node_modules/pimatic/pimatic.js
Could you send me the core dump?

**Comment by jensebub** [comment]
```node --version```
```v0.10.24 ```

```npm list``` 
```/root/pimatic-app
├─┬ pimatic@0.8.43
│ ├── bluebird@2.1.3
│ ├── byline@4.1.1
│ ├─┬ cassert@0.1.2
│ │ └── callsite@1.0.0
│ ├─┬ cjson@0.3.0
│ │ └─┬ jsonlint@1.6.0
│ │   ├── JSV@4.0.2
│ │   └─┬ nomnom@1.8.0
│ │     ├─┬ chalk@0.4.0
│ │     │ ├── ansi-styles@1.0.0
│ │     │ ├── has-color@0.1.7
│ │     │ └── strip-ansi@0.1.1
│ │     └── underscore@1.6.0
│ ├─┬ coffee-script@1.8.0
│ │ └── mkdirp@0.3.5
│ ├── colors@0.6.2
│ ├─┬ convict@0.4.2
│ │ ├── moment@2.3.1
│ │ ├─┬ optimist@0.6.0
│ │ │ ├── minimist@0.0.10
│ │ │ └── wordwrap@0.0.2
│ │ └── validator@1.5.1
│ ├─┬ cross-spawn@0.2.3
│ │ └── lru-cache@2.5.0
│ ├── daemon@1.1.0
│ ├── date-format-lite@0.5.0
│ ├─┬ decl-api@0.0.17
│ │ ├── bluebird@2.3.0
│ │ ├─┬ grunt-contrib-coffee@0.10.1
│ │ │ ├─┬ chalk@0.4.0
│ │ │ │ ├── ansi-styles@1.0.0
│ │ │ │ ├── has-color@0.1.7
│ │ │ │ └── strip-ansi@0.1.1
│ │ │ └─┬ coffee-script@1.7.1
│ │ │   └── mkdirp@0.3.5
│ │ ├── lodash@2.4.1
│ │ └── q@1.0.1 extraneous
│ ├─┬ express@3.4.7
│ │ ├── buffer-crc32@0.2.1
│ │ ├─┬ commander@1.3.2
│ │ │ └── keypress@0.1.0
│ │ ├─┬ connect@2.12.0
│ │ │ ├── batch@0.5.0
│ │ │ ├── bytes@0.2.1
│ │ │ ├─┬ multiparty@2.2.0
│ │ │ │ ├─┬ readable-stream@1.1.10
│ │ │ │ │ ├── core-util-is@1.0.1
│ │ │ │ │ ├── debuglog@0.0.2
│ │ │ │ │ └── string_decoder@0.10.25-1
│ │ │ │ └── stream-counter@0.2.0
│ │ │ ├── negotiator@0.3.0
│ │ │ ├── pause@0.0.1
│ │ │ ├── qs@0.6.6
│ │ │ ├── raw-body@1.1.2
│ │ │ └── uid2@0.0.3
│ │ ├── cookie@0.1.0
│ │ ├── cookie-signature@1.0.1
│ │ ├── debug@0.7.4
│ │ ├── fresh@0.2.0
│ │ ├── merge-descriptors@0.0.1
│ │ ├── methods@0.1.0
│ │ ├── mkdirp@0.3.5
│ │ ├── range-parser@0.0.4
│ │ └─┬ send@0.1.4
│ │   └── mime@1.2.11
│ ├─┬ fs.extra@1.2.1
│ │ ├─┬ fs-extra@0.6.4
│ │ │ ├── jsonfile@1.0.1
│ │ │ ├── ncp@0.4.2
│ │ │ └── rimraf@2.2.6
│ │ ├── mkdirp@0.3.5
│ │ └─┬ walk@2.2.1
│ │   └─┬ forEachAsync@2.2.1
│ │     └── sequence@2.2.1
│ ├── human-format@0.2.0
│ ├─┬ i18n@0.4.1
│ │ ├── debug@0.7.4
│ │ └── sprintf@0.1.3
│ ├─┬ jayschema@0.2.7
│ │ └── when@3.1.0
│ ├─┬ knex@0.7.3
│ │ ├─┬ chalk@0.5.1
│ │ │ ├── ansi-styles@1.1.0
│ │ │ ├── escape-string-regexp@1.0.2
│ │ │ ├─┬ has-ansi@0.1.0
│ │ │ │ └── ansi-regex@0.2.1
│ │ │ ├─┬ strip-ansi@0.3.0
│ │ │ │ └── ansi-regex@0.2.1
│ │ │ └── supports-color@0.2.0
│ │ ├── commander@2.6.0
│ │ ├── generic-pool-redux@0.1.0
│ │ ├── inherits@2.0.1
│ │ ├── interpret@0.3.10
│ │ ├─┬ liftoff@0.13.6
│ │ │ ├── extend@1.3.0
│ │ │ ├─┬ findup-sync@0.1.3
│ │ │ │ └─┬ glob@3.2.11
│ │ │ │   └─┬ minimatch@0.3.0
│ │ │ │     ├── lru-cache@2.5.0
│ │ │ │     └── sigmund@1.0.0
│ │ │ ├── flagged-respawn@0.3.1
│ │ │ └── resolve@1.0.0
│ │ ├── minimist@1.1.0
│ │ ├─┬ mkdirp@0.5.0
│ │ │ └── minimist@0.0.8
│ │ ├─┬ readable-stream@1.1.13
│ │ │ ├── core-util-is@1.0.1
│ │ │ ├── isarray@0.0.1
│ │ │ └── string_decoder@0.10.31
│ │ └─┬ tildify@1.0.0
│ │   └── user-home@1.1.1
│ ├── lodash@2.4.1
│ ├─┬ logrotate-stream@0.2.4
│ │ ├── byt@0.1.0
│ │ ├── log-rotate@0.2.7
│ │ └─┬ optimist@0.6.1
│ │   ├── minimist@0.0.10
│ │   └── wordwrap@0.0.2
│ ├── moment@2.6.0
│ ├── relaxed-json@0.2.4
│ ├── semver@2.2.1
│ ├─┬ socket.io@1.3.3
│ │ ├─┬ debug@2.1.0
│ │ │ └── ms@0.6.2
│ │ ├─┬ engine.io@1.5.1
│ │ │ ├── base64id@0.1.0
│ │ │ ├─┬ debug@1.0.3
│ │ │ │ └── ms@0.6.2
│ │ │ ├─┬ engine.io-parser@1.2.1
│ │ │ │ ├── after@0.8.1
│ │ │ │ ├── arraybuffer.slice@0.0.6
│ │ │ │ ├── base64-arraybuffer@0.1.2
│ │ │ │ ├── blob@0.0.2
│ │ │ │ ├─┬ has-binary@0.1.5
│ │ │ │ │ └── isarray@0.0.1
│ │ │ │ └── utf8@2.0.0
│ │ │ └─┬ ws@0.5.0
│ │ │   ├── nan@1.4.3
│ │ │   ├── options@0.0.6
│ │ │   └── ultron@1.0.1
│ │ ├─┬ has-binary-data@0.1.3
│ │ │ └── isarray@0.0.1
│ │ ├─┬ socket.io-adapter@0.3.1
│ │ │ ├─┬ debug@1.0.2
│ │ │ │ └── ms@0.6.2
│ │ │ ├── object-keys@1.0.1
│ │ │ └─┬ socket.io-parser@2.2.2
│ │ │   ├── benchmark@1.0.0
│ │ │   ├── component-emitter@1.1.2
│ │ │   ├── debug@0.7.4
│ │ │   ├── isarray@0.0.1
│ │ │   └── json3@3.2.6
│ │ ├─┬ socket.io-client@1.3.3
│ │ │ ├── backo2@1.0.2
│ │ │ ├── component-bind@1.0.0
│ │ │ ├── component-emitter@1.1.2
│ │ │ ├── debug@0.7.4
│ │ │ ├─┬ engine.io-client@1.5.1
│ │ │ │ ├── component-inherit@0.0.3
│ │ │ │ ├─┬ debug@1.0.4
│ │ │ │ │ └── ms@0.6.2
│ │ │ │ ├─┬ engine.io-parser@1.2.1
│ │ │ │ │ ├── after@0.8.1
│ │ │ │ │ ├── arraybuffer.slice@0.0.6
│ │ │ │ │ ├── base64-arraybuffer@0.1.2
│ │ │ │ │ ├── blob@0.0.2
│ │ │ │ │ ├─┬ has-binary@0.1.5
│ │ │ │ │ │ └── isarray@0.0.1
│ │ │ │ │ └── utf8@2.0.0
│ │ │ │ ├─┬ has-cors@1.0.3
│ │ │ │ │ └── global@2.0.1
│ │ │ │ ├─┬ parsejson@0.0.1
│ │ │ │ │ └─┬ better-assert@1.0.2
│ │ │ │ │   └── callsite@1.0.0
│ │ │ │ ├─┬ parseqs@0.0.2
│ │ │ │ │ └─┬ better-assert@1.0.2
│ │ │ │ │   └── callsite@1.0.0
│ │ │ │ ├─┬ parseuri@0.0.4
│ │ │ │ │ └─┬ better-assert@1.0.2
│ │ │ │ │   └── callsite@1.0.0
│ │ │ │ ├─┬ ws@0.4.31
│ │ │ │ │ ├── commander@0.6.1
│ │ │ │ │ ├── nan@0.3.2
│ │ │ │ │ ├── options@0.0.6
│ │ │ │ │ └── tinycolor@0.0.1
│ │ │ │ └── xmlhttprequest@1.5.0
│ │ │ ├─┬ has-binary@0.1.6
│ │ │ │ └── isarray@0.0.1
│ │ │ ├── indexof@0.0.1
│ │ │ ├── object-component@0.0.3
│ │ │ ├─┬ parseuri@0.0.2
│ │ │ │ └─┬ better-assert@1.0.2
│ │ │ │   └── callsite@1.0.0
│ │ │ └── to-array@0.1.3
│ │ └─┬ socket.io-parser@2.2.3
│ │   ├── benchmark@1.0.0
│ │   ├── component-emitter@1.1.2
│ │   ├── debug@0.7.4
│ │   ├── isarray@0.0.1
│ │   └── json3@3.2.6
│ ├─┬ source-map-support@0.2.7
│ │ └─┬ source-map@0.1.32
│ │   └── amdefine@0.1.0
│ ├── string@1.8.0
│ └─┬ winston@0.7.2
│   ├── async@0.2.10
│   ├── colors@0.6.2
│   ├── cycle@1.0.3
│   ├── eyes@0.1.8
│   ├── pkginfo@0.3.0
│   ├─┬ request@2.16.6
│   │ ├── aws-sign@0.2.0
│   │ ├── cookie-jar@0.2.0
│   │ ├── forever-agent@0.2.0
│   │ ├─┬ form-data@0.0.10
│   │ │ └─┬ combined-stream@0.0.4
│   │ │   └── delayed-stream@0.0.5
│   │ ├─┬ hawk@0.10.2
│   │ │ ├── boom@0.3.8
│   │ │ ├── cryptiles@0.1.3
│   │ │ ├── hoek@0.7.6
│   │ │ └── sntp@0.1.4
│   │ ├── json-stringify-safe@3.0.0
│   │ ├── mime@1.2.11
│   │ ├── node-uuid@1.4.1
│   │ ├── oauth-sign@0.2.0
│   │ ├── qs@0.5.6
│   │ └── tunnel-agent@0.2.0
│   └── stack-trace@0.0.8
├─┬ pimatic-athome@0.8.2
│ └─┬ serialport@1.4.10
│   ├── async@0.9.0
│   ├── bindings@1.2.1
│   ├── nan@1.3.0
│   ├─┬ node-pre-gyp@0.5.19
│   │ ├─┬ mkdirp@0.5.0
│   │ │ └── minimist@0.0.8
│   │ ├─┬ nopt@2.2.1
│   │ │ └── abbrev@1.0.5
│   │ ├─┬ npmlog@0.0.6
│   │ │ └── ansi@0.2.1
│   │ ├─┬ rc@0.4.0
│   │ │ ├── deep-extend@0.2.10
│   │ │ ├── ini@1.1.0
│   │ │ ├── minimist@0.0.10
│   │ │ └── strip-json-comments@0.1.3
│   │ ├─┬ request@2.36.0
│   │ │ ├── aws-sign2@0.5.0
│   │ │ ├── forever-agent@0.5.2
│   │ │ ├─┬ form-data@0.1.2
│   │ │ │ ├── async@0.2.10
│   │ │ │ └─┬ combined-stream@0.0.4
│   │ │ │   └── delayed-stream@0.0.5
│   │ │ ├─┬ hawk@1.0.0
│   │ │ │ ├── boom@0.4.2
│   │ │ │ ├── cryptiles@0.2.2
│   │ │ │ ├── hoek@0.9.1
│   │ │ │ └── sntp@0.2.4
│   │ │ ├─┬ http-signature@0.10.0
│   │ │ │ ├── asn1@0.1.11
│   │ │ │ ├── assert-plus@0.1.2
│   │ │ │ └── ctype@0.5.2
│   │ │ ├── json-stringify-safe@5.0.0
│   │ │ ├── mime@1.2.11
│   │ │ ├── node-uuid@1.4.1
│   │ │ ├── oauth-sign@0.3.0
│   │ │ ├── qs@0.6.6
│   │ │ ├─┬ tough-cookie@0.12.1
│   │ │ │ └── punycode@1.2.4
│   │ │ └── tunnel-agent@0.4.0
│   │ ├── rimraf@2.2.8
│   │ ├── semver@2.3.0
│   │ ├─┬ tar@0.1.19
│   │ │ ├── block-stream@0.0.7
│   │ │ ├─┬ fstream@0.1.25
│   │ │ │ ├── graceful-fs@2.0.3
│   │ │ │ └── mkdirp@0.3.5
│   │ │ └── inherits@2.0.1
│   │ └─┬ tar-pack@2.0.0
│   │   ├── debug@0.7.4
│   │   ├─┬ fstream@0.1.25
│   │   │ ├── graceful-fs@2.0.3
│   │   │ ├── inherits@2.0.1
│   │   │ └── mkdirp@0.3.5
│   │   ├─┬ fstream-ignore@0.0.7
│   │   │ ├── inherits@2.0.1
│   │   │ └─┬ minimatch@0.2.14
│   │   │   ├── lru-cache@2.5.0
│   │   │   └── sigmund@1.0.0
│   │   ├── graceful-fs@1.2.3
│   │   ├── once@1.1.1
│   │   ├─┬ readable-stream@1.0.27-1
│   │   │ ├── core-util-is@1.0.1
│   │   │ ├── inherits@2.0.1
│   │   │ ├── isarray@0.0.1
│   │   │ └── string_decoder@0.10.25-1
│   │   └── uid-number@0.0.3
│   ├─┬ optimist@0.6.1
│   │ ├── minimist@0.0.10
│   │ └── wordwrap@0.0.2
│   └── sf@0.1.7
├─┬ pimatic-cron@0.8.5
│ ├── chrono-node@0.1.11
│ └─┬ cron@1.0.6
│   └─┬ moment-timezone@0.2.4
│     └── moment@2.9.0
├─┬ pimatic-gpio@0.8.2
│ └─┬ onoff@0.3.2
│   └─┬ epoll@0.1.11
│     ├── bindings@1.2.1
│     └── nan@1.5.3
├─┬ pimatic-homeduino@0.8.36
│ └─┬ homeduino@0.0.26
│   ├── bluebird@2.2.2
│   ├── otaat-repl@1.0.2
│   ├── rfcontroljs@0.0.23
│   └─┬ serialport@1.4.10
│     ├── async@0.9.0
│     ├── bindings@1.2.1
│     ├── nan@1.3.0
│     ├─┬ node-pre-gyp@0.5.19
│     │ ├─┬ mkdirp@0.5.0
│     │ │ └── minimist@0.0.8
│     │ ├─┬ nopt@2.2.1
│     │ │ └── abbrev@1.0.5
│     │ ├─┬ npmlog@0.0.6
│     │ │ └── ansi@0.2.1
│     │ ├─┬ rc@0.4.0
│     │ │ ├── deep-extend@0.2.10
│     │ │ ├── ini@1.1.0
│     │ │ ├── minimist@0.0.10
│     │ │ └── strip-json-comments@0.1.3
│     │ ├─┬ request@2.36.0
│     │ │ ├── aws-sign2@0.5.0
│     │ │ ├── forever-agent@0.5.2
│     │ │ ├─┬ form-data@0.1.2
│     │ │ │ ├── async@0.2.10
│     │ │ │ └─┬ combined-stream@0.0.4
│     │ │ │   └── delayed-stream@0.0.5
│     │ │ ├─┬ hawk@1.0.0
│     │ │ │ ├── boom@0.4.2
│     │ │ │ ├── cryptiles@0.2.2
│     │ │ │ ├── hoek@0.9.1
│     │ │ │ └── sntp@0.2.4
│     │ │ ├─┬ http-signature@0.10.0
│     │ │ │ ├── asn1@0.1.11
│     │ │ │ ├── assert-plus@0.1.2
│     │ │ │ └── ctype@0.5.2
│     │ │ ├── json-stringify-safe@5.0.0
│     │ │ ├── mime@1.2.11
│     │ │ ├── node-uuid@1.4.1
│     │ │ ├── oauth-sign@0.3.0
│     │ │ ├── qs@0.6.6
│     │ │ ├─┬ tough-cookie@0.12.1
│     │ │ │ └── punycode@1.2.4
│     │ │ └── tunnel-agent@0.4.0
│     │ ├── rimraf@2.2.8
│     │ ├── semver@2.3.0
│     │ ├─┬ tar@0.1.19
│     │ │ ├── block-stream@0.0.7
│     │ │ ├─┬ fstream@0.1.25
│     │ │ │ ├── graceful-fs@2.0.3
│     │ │ │ └── mkdirp@0.3.5
│     │ │ └── inherits@2.0.1
│     │ └─┬ tar-pack@2.0.0
│     │   ├── debug@0.7.4
│     │   ├─┬ fstream@0.1.25
│     │   │ ├── graceful-fs@2.0.3
│     │   │ ├── inherits@2.0.1
│     │   │ └── mkdirp@0.3.5
│     │   ├─┬ fstream-ignore@0.0.7
│     │   │ ├── inherits@2.0.1
│     │   │ └─┬ minimatch@0.2.14
│     │   │   ├── lru-cache@2.5.0
│     │   │   └── sigmund@1.0.0
│     │   ├── graceful-fs@1.2.3
│     │   ├── once@1.1.1
│     │   ├─┬ readable-stream@1.0.27-1
│     │   │ ├── core-util-is@1.0.1
│     │   │ ├── inherits@2.0.1
│     │   │ ├── isarray@0.0.1
│     │   │ └── string_decoder@0.10.25-1
│     │   └── uid-number@0.0.3
│     ├─┬ optimist@0.6.1
│     │ ├── minimist@0.0.10
│     │ └── wordwrap@0.0.2
│     └── sf@0.1.7
├─┬ pimatic-lcd@0.8.2
│ └─┬ i2c-lcd@1.0.0
│   ├── bluebird@2.3.11
│   └─┬ i2c@0.1.6
│     ├── bindings@1.1.1
│     ├── coffee-script@1.3.3
│     ├── repl@0.1.3
│     └── underscore@1.2.4
├── pimatic-links@0.8.5
├─┬ pimatic-log-reader@0.8.2
│ ├── line-by-line@0.1.3
│ └── tail@0.4.0
├─┬ pimatic-mail@0.8.2
│ └─┬ nodemailer@0.6.5
│   ├── directmail@0.1.8
│   ├── he@0.3.6
│   ├─┬ mailcomposer@0.2.12
│   │ ├─┬ dkim-signer@0.1.2
│   │ │ └── punycode@1.2.4
│   │ ├─┬ follow-redirects@0.0.3
│   │ │ └── underscore@1.7.0
│   │ ├── mime@1.2.11
│   │ └─┬ mimelib@0.2.18
│   │   ├── addressparser@0.2.1
│   │   └─┬ encoding@0.1.11
│   │     └── iconv-lite@0.4.6
│   ├── public-address@0.1.1
│   ├─┬ readable-stream@1.1.13
│   │ ├── core-util-is@1.0.1
│   │ ├── inherits@2.0.1
│   │ ├── isarray@0.0.1
│   │ └── string_decoder@0.10.31
│   └─┬ simplesmtp@0.3.34
│     ├── rai@0.1.11
│     └── xoauth2@0.1.8
├─┬ pimatic-max@0.8.9
│ └── max-control@0.0.1 (git+https://github.com/sweetpi/max-control#70dfbae2b8078b10e17a1ce9ef1e18e0c64db847)
├─┬ pimatic-mobile-frontend@0.8.42
│ ├── colour.js@1.5.2
│ ├─┬ jade@1.1.4
│ │ ├── character-parser@1.2.0
│ │ ├── commander@2.1.0
│ │ ├─┬ constantinople@1.0.2
│ │ │ └─┬ uglify-js@2.4.15
│ │ │   ├── async@0.2.10
│ │ │   ├─┬ optimist@0.3.7
│ │ │   │ └── wordwrap@0.0.2
│ │ │   ├─┬ source-map@0.1.34
│ │ │   │ └── amdefine@0.1.0
│ │ │   └── uglify-to-browserify@1.0.2
│ │ ├── mkdirp@0.3.5
│ │ ├─┬ monocle@1.1.51
│ │ │ └─┬ readdirp@0.2.5
│ │ │   └─┬ minimatch@1.0.0
│ │ │     ├── lru-cache@2.5.0
│ │ │     └── sigmund@1.0.0
│ │ ├─┬ transformers@2.1.0
│ │ │ ├─┬ css@1.0.8
│ │ │ │ ├── css-parse@1.0.4
│ │ │ │ └── css-stringify@1.0.5
│ │ │ ├─┬ promise@2.0.0
│ │ │ │ └── is-promise@1.0.1
│ │ │ └─┬ uglify-js@2.2.5
│ │ │   ├─┬ optimist@0.3.7
│ │ │   │ └── wordwrap@0.0.2
│ │ │   └─┬ source-map@0.1.40
│ │ │     └── amdefine@0.1.0
│ │ └─┬ with@2.0.0
│ │   └─┬ uglify-js@2.4.0
│ │     ├── async@0.2.10
│ │     ├─┬ optimist@0.3.7
│ │     │ └── wordwrap@0.0.2
│ │     ├─┬ source-map@0.1.40
│ │     │ └── amdefine@0.1.0
│ │     └── uglify-to-browserify@1.0.2
│ ├─┬ jqmthemer@0.0.1
│ │ └── bluebird@2.2.2
│ ├─┬ nap@0.8.0
│ │ ├─┬ coffee-script@1.8.0
│ │ │ └── mkdirp@0.3.5
│ │ ├── file@0.2.2
│ │ ├─┬ glob@3.2.11
│ │ │ ├── inherits@2.0.1
│ │ │ └─┬ minimatch@0.3.0
│ │ │   ├── lru-cache@2.5.0
│ │ │   └── sigmund@1.0.0
│ │ ├─┬ mkdirp@0.5.0
│ │ │ └── minimist@0.0.8
│ │ ├── rimraf@2.2.8
│ │ ├── sqwish@0.2.2
│ │ ├─┬ uglify-js@2.4.15
│ │ │ ├── async@0.2.10
│ │ │ ├─┬ optimist@0.3.7
│ │ │ │ └── wordwrap@0.0.2
│ │ │ ├─┬ source-map@0.1.34
│ │ │ │ └── amdefine@0.1.0
│ │ │ └── uglify-to-browserify@1.0.2
│ │ ├── underscore@1.7.0
│ │ └── underscore.string@2.3.3
│ └── render-appcache-manifest@0.3.0
├─┬ pimatic-ping@0.8.3
│ └─┬ net-ping@1.1.11
│   └── raw-socket@1.2.2
├─┬ pimatic-play@0.8.0
│ └─┬ play@0.5.0 (git+https://github.com/Marak/play.js.git#d3ca7a04d1bd58c3ad72df3088f92985742e41cc)
│   └── colors@1.0.3
├── pimatic-shell-execute@0.8.6
├─┬ pimatic-sunrise@0.8.0
│ └── suncalc@1.4.0
├─┬ pimatic-sysinfo@0.8.10
│ └─┬ nsutil@0.1.3 (git+https://github.com/sweetpi/nsutil.git#0dd938799f326357e7613b75f4ad3fa3432ec409)
│   └─┬ mocha@2.1.0
│     ├── commander@2.3.0
│     ├─┬ debug@2.0.0
│     │ └── ms@0.6.2
│     ├── diff@1.0.8
│     ├── escape-string-regexp@1.0.2
│     ├─┬ glob@3.2.3
│     │ ├── graceful-fs@2.0.3
│     │ ├── inherits@2.0.1
│     │ └─┬ minimatch@0.2.14
│     │   ├── lru-cache@2.5.0
│     │   └── sigmund@1.0.0
│     ├── growl@1.8.1
│     ├─┬ jade@0.26.3
│     │ ├── commander@0.6.1
│     │ └── mkdirp@0.3.0
│     └─┬ mkdirp@0.5.0
│       └── minimist@0.0.8
├── pimatic-voice-recognition@0.8.0
├─┬ pimatic-weather@0.8.11
│ └─┬ weather-js@1.0.1
│   ├─┬ request@2.53.0
│   │ ├── aws-sign2@0.5.0
│   │ ├─┬ bl@0.9.4
│   │ │ └─┬ readable-stream@1.0.33
│   │ │   ├── core-util-is@1.0.1
│   │ │   ├── inherits@2.0.1
│   │ │   ├── isarray@0.0.1
│   │ │   └── string_decoder@0.10.31
│   │ ├── caseless@0.9.0
│   │ ├─┬ combined-stream@0.0.7
│   │ │ └── delayed-stream@0.0.5
│   │ ├── forever-agent@0.5.2
│   │ ├─┬ form-data@0.2.0
│   │ │ └── async@0.9.0
│   │ ├─┬ hawk@2.3.1
│   │ │ ├── boom@2.6.1
│   │ │ ├── cryptiles@2.0.4
│   │ │ ├── hoek@2.11.0
│   │ │ └── sntp@1.0.9
│   │ ├─┬ http-signature@0.10.1
│   │ │ ├── asn1@0.1.11
│   │ │ ├── assert-plus@0.1.5
│   │ │ └── ctype@0.5.3
│   │ ├── isstream@0.1.1
│   │ ├── json-stringify-safe@5.0.0
│   │ ├─┬ mime-types@2.0.8
│   │ │ └── mime-db@1.6.1
│   │ ├── node-uuid@1.4.2
│   │ ├── oauth-sign@0.6.0
│   │ ├── qs@2.3.3
│   │ ├── stringstream@0.0.4
│   │ ├─┬ tough-cookie@0.12.1
│   │ │ └── punycode@1.3.2
│   │ └── tunnel-agent@0.4.0
│   └─┬ xml2js@0.4.4
│     ├── sax@0.6.1
│     └─┬ xmlbuilder@2.5.0
│       └── lodash@3.0.1
└─┬ sqlite3@3.0.4
  ├── nan@1.4.3
  └─┬ node-pre-gyp@0.6.1
    ├─┬ mkdirp@0.5.0
    │ └── minimist@0.0.8
    ├─┬ nopt@3.0.1
    │ └── abbrev@1.0.5
    ├─┬ npmlog@0.1.1
    │ └── ansi@0.3.0
    ├─┬ rc@0.5.4
    │ ├── deep-extend@0.2.11
    │ ├── ini@1.1.0
    │ ├── minimist@0.0.10
    │ └── strip-json-comments@0.1.3
    ├─┬ request@2.48.0
    │ ├── aws-sign2@0.5.0
    │ ├─┬ bl@0.9.3
    │ │ └─┬ readable-stream@1.0.33
    │ │   ├── core-util-is@1.0.1
    │ │   ├── inherits@2.0.1
    │ │   ├── isarray@0.0.1
    │ │   └── string_decoder@0.10.31
    │ ├── caseless@0.7.0
    │ ├─┬ combined-stream@0.0.7
    │ │ └── delayed-stream@0.0.5
    │ ├── forever-agent@0.5.2
    │ ├─┬ form-data@0.1.4
    │ │ ├── async@0.9.0
    │ │ └── mime@1.2.11
    │ ├─┬ hawk@1.1.1
    │ │ ├── boom@0.4.2
    │ │ ├── cryptiles@0.2.2
    │ │ ├── hoek@0.9.1
    │ │ └── sntp@0.2.4
    │ ├─┬ http-signature@0.10.0
    │ │ ├── asn1@0.1.11
    │ │ ├── assert-plus@0.1.2
    │ │ └── ctype@0.5.2
    │ ├── json-stringify-safe@5.0.0
    │ ├── mime-types@1.0.2
    │ ├── node-uuid@1.4.1
    │ ├── oauth-sign@0.5.0
    │ ├── qs@2.3.3
    │ ├── stringstream@0.0.4
    │ ├─┬ tough-cookie@0.12.1
    │ │ └── punycode@1.3.2
    │ └── tunnel-agent@0.4.0
    ├── rimraf@2.2.8
    ├── semver@4.1.0
    ├─┬ tar@1.0.2
    │ ├── block-stream@0.0.7
    │ ├─┬ fstream@1.0.2
    │ │ └── graceful-fs@3.0.4
    │ └── inherits@2.0.1
    └─┬ tar-pack@2.0.0
      ├── debug@0.7.4
      ├─┬ fstream@0.1.31
      │ ├── graceful-fs@3.0.4
      │ └── inherits@2.0.1
      ├─┬ fstream-ignore@0.0.7
      │ ├── inherits@2.0.1
      │ └─┬ minimatch@0.2.14
      │   ├── lru-cache@2.5.0
      │   └── sigmund@1.0.0
      ├── graceful-fs@1.2.3
      ├── once@1.1.1
      ├─┬ readable-stream@1.0.33
      │ ├── core-util-is@1.0.1
      │ ├── inherits@2.0.1
      │ ├── isarray@0.0.1
      │ └── string_decoder@0.10.31
      ├─┬ tar@0.1.20
      │ ├── block-stream@0.0.7
      │ └── inherits@2.0.1
      └── uid-number@0.0.3

npm ERR! extraneous: q@1.0.1 /root/pimatic-app/node_modules/pimatic/node_modules/decl-api/node_modules/q
npm ERR! not ok code 0
```

```ls -alh ```
```
insgesamt 117M
drwxr-xr-x   6 root root 4,0K Feb  7 17:55 ./
drwx------  16 root root 4,0K Feb  7 17:59 ../
-rwxr-xr-x   1 root root  42K Dez 27 18:46 alarm.wav*
-rw-r--r--   1 root root  45K Feb  7 17:55 config.json
-rw-------   1 root root 157M Feb  7 17:12 core
-rwxr-xr-x   1 root root 1,2K Jan  4 15:56 duo*
-rwxr-xr-x   1 root root  648 Jan  4 15:56 getstate.sh*
-rwxr-xr-x   1 root root  242 Jan  4 15:56 IP.sh*
drwxrwxrwx   3 root root 4,0K Jan 27 18:13 .node-gyp/
drwxr-xr-x  22 root root 4,0K Feb  7 15:40 node_modules/
drwxrwxrwx 165 root root  12K Feb  7 15:41 .npm/
-rw-rw-rw-   1 root root 327K Feb  7 17:55 pimatic-daemon.log
-rw-r--r--   1 root root 6,9M Feb  7 17:55 pimatic-database.sqlite
-rw-r--r--   1 root root  979 Jan 27 19:52 pimatic-init-d
drwxrwxrwx   2 root root 4,0K Feb  7 15:42 tmp/
```

@sweetpi the coredump is about 157M uploading to my cloud is taking a while ;)
i go ahaed and mail the rest

**Comment by Icesory** [comment]
@sweetpi I have updated to day my pimatic to the latest version but now I got the pimatic-homeduino cannot read length failure.

**Comment by sweetpi** [comment]
@Icesory Do have a core dump? Can you use gdb to get a stack trace? (For example like in http://www.pilight.org/development/debugging/)

The problem is, that I can't reproduce the segmentation fault...

**Comment by sweetpi** [comment]
@Icesory Please also test if this fix solves both errors: https://github.com/sweetpi/node-serialport/commit/e013d1ed6c9dc2d248c5657f6c4c6e0f4e80becc

**Comment by Icesory** [comment]
The problem was the Update process through the pimatic web end. It has corrupt the installation. 
I made a "npm install pimatic-homeduino" and now it works again.

So i dont have a core dumb and i cant reproduce the failure :-(

**Comment by Icesory** [comment]
```console
12:48:24.380 [pimatic-mobile-frontend] rendering html finished
12:48:24.543 [pimatic] listening for http-request on port 80...

Program received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) 
```
I am not sure how i get a core dumb.

**Comment by sweetpi** [comment]
Could you type `bt` in gdb to get the full backtrace?

**Comment by Icesory** [comment]
I can see a strange failure in this.
First i tried the gdb as user pi
```
sudo gdb node
(gdb) run /xxx/pimatic.js
```
this creates the segfault

then i logged in to the root account an tried it again and it dont failed.
I switch back to the pi account and retrying the procedure.
Now i got a other segfault
```

13:10:46.817 [pimatic-mobile-frontend] rendering html finished
13:10:46.978 [pimatic] listening for http-request on port 80...

Program received signal SIGSEGV, Segmentation fault.
0x0017a4e4 in v8::Object::Get(unsigned int) ()
(gdb)
```


```
(gdb) bt
#0  0x0017a4e4 in v8::Object::Get(unsigned int) ()
#1  0xb4ad9b6c in SerialportPoller::callCallback(int) ()
   from /home/pi/pimatic-app/node_modules/pimatic-homeduino/node_modules/homeduino/node_modules/serialport/build/serialport/v1.4.10/Release/node-v11-linux-arm/serialport.node
#2  0x00527d10 in uv__poll_io (loop=<optimized out>, w=0x7ddb90,
    events=<optimized out>) at ../deps/uv/src/unix/poll.c:50
#3  0x0052f1dc in uv__io_poll (loop=0x6ea788, timeout=823)
    at ../deps/uv/src/unix/linux-core.c:263
#4  0x005240a4 in uv_run (loop=0x6ea788, mode=<optimized out>)
    at ../deps/uv/src/unix/core.c:317
#5  0x003f8404 in node::Start(int, char**) ()
#6  0xb6d0381c in __libc_start_main () from /lib/arm-linux-gnueabihf/libc.so.6
#7  0x0016adfc in _start ()
```

**Comment by sweetpi** [comment]
Wow that stack trace looks promising. Have to prepare stuff for next week today, so no fixing... But that finally looks like something to work with :)

**Comment by Icesory** [comment]
And the other segfault
Now i need many restarts to get this. But there are not really information in it.
```console
14:25:39.279 [pimatic-mobile-frontend] rendering html finished
14:25:39.441 [pimatic] listening for http-request on port 80...

Program received signal SIGSEGV, Segmentation fault.
0x656c6260 in ?? ()
(gdb) bt
#0  0x656c6260 in ?? ()
#1  0x0052f1dc in uv__io_poll (loop=0x6ea788, timeout=1005)
    at ../deps/uv/src/unix/linux-core.c:263
#2  0x005240a4 in uv_run (loop=0x6ea788, mode=<optimized out>)
    at ../deps/uv/src/unix/core.c:317
#3  0x003f8404 in node::Start(int, char**) ()
#4  0xb6d0381c in __libc_start_main () from /lib/arm-linux-gnueabihf/libc.so.6
#5  0x0016adfc in _start ()
(gdb) frame 5
#5  0x0016adfc in _start ()
(gdb) frame 4
#4  0xb6d0381c in __libc_start_main () from /lib/arm-linux-gnueabihf/libc.so.6
(gdb) frame 3
#3  0x003f8404 in node::Start(int, char**) ()
(gdb) frame 2
#2  0x005240a4 in uv_run (loop=0x6ea788, mode=<optimized out>)
    at ../deps/uv/src/unix/core.c:317
317     ../deps/uv/src/unix/core.c: No such file or directory.
(gdb) frame 1
#1  0x0052f1dc in uv__io_poll (loop=0x6ea788, timeout=1005)
    at ../deps/uv/src/unix/linux-core.c:263
263     ../deps/uv/src/unix/linux-core.c: No such file or directory.
(gdb) frame 0
#0  0x656c6260 in ?? ()
(gdb)
```

**Comment by sweetpi** [comment]
I've released pimatic-homeduino v0.8.37 with increased timeouts, this should limit the problem till there is a better solution.

**Comment by jensebub** [comment]
great!
that solved my issue

Thanx
jensebub

**Comment by kjdijkema** [comment]
@sweetpi I installed pimatic from scratch yesterday and it still works fine. Issue seems to be solved on my side.

**Comment by Yves911** [comment]
@sweetpi it also seems to be much better for me too (using it with my large DB)
Thanks

**Comment by DDNRN** [comment]
@sweetpi   
No problems anymore. It is no starting even with  "pimatic service restart" and from Browser "restart".
