### ISSUE TITLE
Two pimatic issues after upgrade

### ISSUE THREAD

**Issue by edautz** [pimatic/pimatic#539]
I am using Pimatic for several months now. It works wunderfull fine and easy.
But after the last upgrade I notices two issues:

1: Pimatic will not stop anymore with the command "sudo service pimatic stop"

I got the following error:

Sending SIGTERM to pimatic, waiting for process exit...
Process didn't shutdown in time, sending signal SIGTERM to pimatic, waiting for process exit...
Process didn't shutdown in time, sending signal SIGQUIT to pimatic, waiting for process exit...
This will contnue........

2: I cannot display a graph anymore with safari iphone/ipad. When i use chrome on my ipad, it works.
When i try to open the graph, the graph banner simply disappear.

I upgraded pimatic from 0.8.37 to 0.8.44 and Mobile-frontend from 0.8.39 to 0.8.43 and a few other plugins as well.

**Comment by sweetpi** [comment]
> 1: Pimatic will not stop anymore with the command "sudo service pimatic stop"

What does the logfile say?

> 2: I cannot display a graph anymore with safari iphone/ipad. When i use crome on my ipad, it works.
> When i try to open the graph, the graph banner simply disappear.

I will look into it.

**Comment by edautz** [comment]
Ok. I updated yesterday evening I didn't notice that pimtaic was updated to 0.8.45.
I will test it.

The logfiles says:

10:18:05.924 [pimatic-homeduino] info: Connected to homeduino device.
12:52:05.958 [pimatic] info: Flushing database to disk, please wait...
12:52:06.895 [pimatic] info: Flushing database to disk, please wait...Done.

After that no more entries.

**Comment by edautz** [comment]
I upgraded pimatic to 0.8.45 and I can stop pimatic with the command "sudo service pimatic stop". Works fine again. Thnx for that.

The second problem with the graph when using Safari still exists.

**Comment by sweetpi** [comment]
I've released pimatic-mobile-frontend v0.8.44 which should fix the issue with the graph tooltip button. Please reopen if there are still problems.

**Comment by edautz** [comment]
Pitty, but this upgrade didn't solve the problem. 
Even worse, with chrome on my Ipad, it doen't work also anymore.

The exact problem is, when i tip on an temperature value, A little banner appears with the temperature and a timestamp and to the right a Graph Field.

When pressing the Graph field, the banner disappears without any action.

**Comment by sweetpi** [comment]
Could you try in an incognito tab? I'm pretty sure it's just caching. The changes are only picked up after an additional reload.

I tested on safari iphone emulator and chrome desktop + mobile.

**Comment by edautz** [comment]
OK. I opened a new tab and it worked again!!
Thnx very much.
