### ISSUE TITLE
Weather plugin stopped working

### ISSUE THREAD

**Issue by koffienl** [pimatic/pimatic#629]
I have 3 seperate pimatic installs, they all stopped receiving weather updates since 23:40 april 2. Anyone know what's going on ? What provider is the weather plugin currently using to get it's information ? 
<code>error [pimatic-weather]: Request failed (406)</code>

**Comment by sweetpi** [comment]
It uses msn. I think you have to switch to the openweather plugin.

**Comment by ErikCoen** [comment]
I just updated the pimatic-weather. Suddenly, there is no weather data available. I got an error "attribute err" is missing. I am not sure if I am spelling this correctly.

**Comment by koffienl** [comment]
Thanks, wasn't aware of the fact we could choose from 2 different weather plugins :)
I'll try an update with the pimatic-weather plugin (the openwaether gives error during the install)

**Comment by sweetpi** [comment]
Could you post the error?

**Comment by sweetpi** [comment]
@ErikCoen Thanks for reporting should be fixed.

**Comment by koffienl** [comment]
''''
pi@raspipool ~/pimatic-app $ sudo npm install pimatic-openweather
npm http GET https://registry.npmjs.org/pimatic-openweather
npm http 304 https://registry.npmjs.org/pimatic-openweather
npm http GET https://github.com/sweetpi/node-openweathermap.git#master
npm http GET https://registry.npmjs.org/promise-retryer/0.0.1
npm http 200 https://github.com/sweetpi/node-openweathermap.git#master
npm ERR! not a package /root/tmp/npm-13550-REj4s9ab/1428070926125-0.27931936155073345/tmp.tgz
npm ERR! Error: ENOENT, open '/root/tmp/npm-13550-REj4s9ab/1428070926125-0.27931936155073345/package/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.12.20+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pimatic-openweather"
npm ERR! cwd /home/pi/pimatic-app
npm ERR! node -v v0.10.21
npm ERR! npm -v 1.3.11
npm ERR! path /root/tmp/npm-13550-REj4s9ab/1428070926125-0.27931936155073345/package/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm http 304 https://registry.npmjs.org/promise-retryer/0.0.1
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/pimatic-app/npm-debug.log
npm ERR! not ok code 0
''''

**Comment by sweetpi** [comment]
@koffienl Thanks, too. Should be working now.

**Comment by ErikCoen** [comment]
Hi all,

Updating to newest version 0.14 does not solve the issue. I got another
error. Hereby my log file.

Erik

2015-04-03 17:00 GMT+02:00 sweet pi - sweet home <notifications@github.com>:

> @koffienl <https://github.com/koffienl> Thanks, too. Should be working
> now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pimatic/pimatic/issues/629#issuecomment-89312534>.
>

11:29:12.396 [pimatic-weather] error: Request failed (406)
11:29:12.399 [pimatic-weather] debug: Error: Request failed (406)
11:29:12.399 [pimatic-weather] debug:>    at maybeWrapAsError (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebi$
11:29:12.399 [pimatic-weather] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise$
11:29:12.399 [pimatic-weather] debug:>    at Request._callback (/home/pi/pimatic-app/node_modules/pimatic-weather/node_modul$
11:29:12.399 [pimatic-weather] debug:>    at Request.self.callback (/home/pi/pimatic-app/node_modules/pimatic-weather/node_m$
11:29:12.399 [pimatic-weather] debug:>    at Request.EventEmitter.emit (events.js:98:17)
11:29:12.399 [pimatic-weather] debug:>    at Request.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-weather/node_mod$
11:29:12.399 [pimatic-weather] debug:>    at Request.EventEmitter.emit (events.js:117:20)
11:29:12.399 [pimatic-weather] debug:>    at IncomingMessage.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-weather/$
11:29:12.399 [pimatic-weather] debug:>    at IncomingMessage.EventEmitter.emit (events.js:117:20)
11:29:12.399 [pimatic-weather] debug:>    at _stream_readable.js:920:16
11:29:12.399 [pimatic-weather] debug:>    at process._tickCallback (node.js:415:13)
...

============Updated to version 0.14

15:57:32.525 [pimatic] info: Installing: "pimatic-weather" from precompiled source (node-11-armhf-linux-0.8.13)
...
15:58:17.155 [pimatic] error: Could not get attribute value of Weer in Mierlo.status: err is not defined
15:58:17.159 [pimatic] debug: ReferenceError: err is not defined
15:58:17.159 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic-weather/weather.coffee:66:26
15:58:17.159 [pimatic] debug:>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/uti$
15:58:17.159 [pimatic] debug:>    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modul$
15:58:17.159 [pimatic] debug:>    at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebi$
15:58:17.159 [pimatic] debug:>    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebir$
15:58:17.159 [pimatic] debug:>    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/m$
15:58:17.159 [pimatic] debug:>    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/$
15:58:17.159 [pimatic] debug:>    at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/m$
15:58:17.159 [pimatic] debug:>    at process._tickCallback (node.js:415:13)
15:58:17.163 [pimatic] error: Could not get attribute value of Weer in Mierlo.windspeed: err is not defined
15:58:17.169 [pimatic] debug: ReferenceError: err is not defined
15:58:17.169 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic-weather/weather.coffee:66:26
15:58:17.169 [pimatic] debug:>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/uti$
15:58:17.169 [pimatic] debug:>    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modul$
15:58:17.169 [pimatic] debug:>    at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebi$
15:58:17.169 [pimatic] debug:>    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebir$
15:58:17.169 [pimatic] debug:>    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/m$
15:58:17.169 [pimatic] debug:>    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/$
15:58:17.169 [pimatic] debug:>    at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/m$
15:58:17.169 [pimatic] debug:>    at process._tickCallback (node.js:415:13)
15:58:17.172 [pimatic] error: Could not get attribute value of Weer in Mierlo.temperature: err is not defined
15:58:17.282 [pimatic] debug: ReferenceError: err is not defined
15:58:17.282 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic-weather/weather.coffee:66:26
15:58:17.282 [pimatic] debug:>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/uti$
15:58:17.282 [pimatic] debug:>    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modul$
15:58:17.282 [pimatic] debug:>    at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebi$
15:58:17.282 [pimatic] debug:>    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebir$
15:58:17.282 [pimatic] debug:>    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/m$
15:58:17.282 [pimatic] debug:>    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/$
15:58:17.282 [pimatic] debug:>    at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/m$
15:58:17.282 [pimatic] debug:>    at process._tickCallback (node.js:415:13)
15:58:17.285 [pimatic] warn: Could not update variable weather.humidity: err is not defined
15:58:17.287 [pimatic] debug: ReferenceError: err is not defined
15:58:17.287 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic-weather/weather.coffee:66:26
15:58:17.287 [pimatic] debug:>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/uti$
15:58:17.287 [pimatic] debug:>    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modul$
15:58:17.287 [pimatic] debug:>    at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebi$
15:58:17.287 [pimatic] debug:>    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebir$
15:58:17.287 [pimatic] debug:>    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/m$
15:58:17.287 [pimatic] debug:>    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/$
15:58:17.287 [pimatic] debug:>    at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/m$
15:58:17.287 [pimatic] debug:>    at process._tickCallback (node.js:415:13)

error [pimatic]: Could not get attribute value of Weer in Mierlo.humidity: err is not defined
16:05:04error [pimatic]: Could not get attribute value of Weer in Mierlo.temperature: err is not defined
16:05:04error [pimatic]: Could not get attribute value of Weer in Mierlo.windspeed: err is not defined
16:05:04error [pimatic]: Could not get attribute value of Weer in Mierlo.status: err is not defined

..


============Updated to version 0.14

17:24:05.352 [pimatic] info: Installing: "pimatic-weather" from precompiled source (node-11-armhf-linux-0.8.14)
...
2015-04-03 17:24:52error [pimatic]: Could not get attribute value of Weer in Mierlo.humidity: Cannot read property 'humidity' of undefined
17:24:52error [pimatic]: Could not get attribute value of Weer in Mierlo.temperature: Cannot read property 'temperature' of undefined
17:24:52error [pimatic]: Could not get attribute value of Weer in Mierlo.windspeed: Cannot read property 'windspeed' of undefined
17:24:52error [pimatic]: Could not get attribute value of Weer in Mierlo.status: Cannot read property 'skytext' of undefined

17:24:51.982 [pimatic-weather] error: Request failed (406)
17:24:51.995 [pimatic-weather] debug: Error: Request failed (406)
17:24:51.995 [pimatic-weather] debug:>    at maybeWrapAsError (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebi$
17:24:51.995 [pimatic-weather] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise$
17:24:51.995 [pimatic-weather] debug:>    at Request._callback (/home/pi/pimatic-app/node_modules/pimatic-weather/node_modul$
17:24:51.995 [pimatic-weather] debug:>    at Request.self.callback (/home/pi/pimatic-app/node_modules/pimatic-weather/node_m$
17:24:51.995 [pimatic-weather] debug:>    at Request.EventEmitter.emit (events.js:98:17)
17:24:51.995 [pimatic-weather] debug:>    at Request.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-weather/node_mod$
17:24:51.995 [pimatic-weather] debug:>    at Request.EventEmitter.emit (events.js:117:20)
17:24:51.995 [pimatic-weather] debug:>    at IncomingMessage.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-weather/$
17:24:51.995 [pimatic-weather] debug:>    at IncomingMessage.EventEmitter.emit (events.js:117:20)
17:24:51.995 [pimatic-weather] debug:>    at _stream_readable.js:920:16
17:24:51.995 [pimatic-weather] debug:>    at process._tickCallback (node.js:415:13)
17:24:52.202 [pimatic] error: Could not get attribute value of Weer in Mierlo.status: Cannot read property 'skytext' of unde$
17:24:52.206 [pimatic] debug: TypeError: Cannot read property 'skytext' of undefined
17:24:52.206 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic-weather/weather.coffee:72:68
17:24:52.206 [pimatic] debug:>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/uti$
17:24:52.206 [pimatic] debug:>    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modul$
17:24:52.206 [pimatic] debug:>    at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebi$
17:24:52.206 [pimatic] debug:>    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebir$
17:24:52.206 [pimatic] debug:>    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/m$
17:24:52.206 [pimatic] debug:>    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/$
17:24:52.206 [pimatic] debug:>    at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/m$
17:24:52.206 [pimatic] debug:>    at process._tickCallback (node.js:415:13)
17:24:52.215 [pimatic] error: Could not get attribute value of Weer in Mierlo.windspeed: Cannot read property 'windspeed' of$
17:24:52.218 [pimatic] debug: TypeError: Cannot read property 'windspeed' of undefined
17:24:52.218 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic-weather/weather.coffee:73:79
17:24:52.218 [pimatic] debug:>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/uti$
17:24:52.218 [pimatic] debug:>    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modul$
17:24:52.218 [pimatic] debug:>    at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebi$
17:24:52.218 [pimatic] debug:>    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebir$
17:24:52.218 [pimatic] debug:>    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/m$
17:24:52.218 [pimatic] debug:>    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/$
17:24:52.218 [pimatic] debug:>    at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/m$
17:24:52.218 [pimatic] debug:>    at process._tickCallback (node.js:415:13)
17:24:52.246 [pimatic] debug: TypeError: Cannot read property 'windspeed' of undefined
17:24:52.246 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic-weather/weather.coffee:73:79
17:24:52.246 [pimatic] debug:>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/uti$
17:24:52.246 [pimatic] debug:>    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modul$
17:24:52.246 [pimatic] debug:>    at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebi$
17:24:52.246 [pimatic] debug:>    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebir$
17:24:52.246 [pimatic] debug:>    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/m$
17:24:52.246 [pimatic] debug:>    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/$
17:24:52.246 [pimatic] debug:>    at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/m$
17:24:52.246 [pimatic] debug:>    at process._tickCallback (node.js:415:13)
17:24:52.250 [pimatic] warn: Could not update variable weather.temperature: Cannot read property 'temperature' of undefined
17:24:52.253 [pimatic] debug: TypeError: Cannot read property 'temperature' of undefined
17:24:52.253 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic-weather/weather.coffee:70:80
17:24:52.253 [pimatic] debug:>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/uti$
17:24:52.253 [pimatic] debug:>    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modul$
17:24:52.253 [pimatic] debug:>    at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebi$
17:24:52.253 [pimatic] debug:>    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebir$
17:24:52.253 [pimatic] debug:>    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/m$
17:24:52.253 [pimatic] debug:>    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/$
17:24:52.253 [pimatic] debug:>    at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/m$
17:24:52.253 [pimatic] debug:>    at process._tickCallback (node.js:415:13)
17:24:52.263 [pimatic] warn: Could not update variable weather.humidity: Cannot read property 'humidity' of undefined
17:24:52.266 [pimatic] debug: TypeError: Cannot read property 'humidity' of undefined
17:24:52.266 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic-weather/weather.coffee:71:77
17:24:52.266 [pimatic] debug:>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/uti$
17:24:52.266 [pimatic] debug:>    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modul$
17:24:52.266 [pimatic] debug:>    at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebi$
17:24:52.266 [pimatic] debug:>    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebir$
17:24:52.266 [pimatic] debug:>    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/m$
17:24:52.266 [pimatic] debug:>    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/$
17:24:52.266 [pimatic] debug:>    at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/m$
17:24:52.266 [pimatic] debug:>    at process._tickCallback (node.js:415:13)

**Comment by sweetpi** [comment]
> Updating to newest version 0.14 does not solve the issue. I got another
> error. Hereby my log file.

I fixed that error, but still not working because msn changed / removed the api like @koffienl already mentioned. Try to change to openweather.

**Comment by koffienl** [comment]
I have switched ti openweather :)

**Comment by NietGiftig** [comment]
I use openweather but the last days the results seems to update in hours.
I have the timeout on 300000 (5 minutes) but 

![openweather](https://cloud.githubusercontent.com/assets/1190241/6993074/f5c05aa4-dae8-11e4-99c7-23692cc6628a.jpg)

**Comment by pimagical** [comment]
Use Pimatic-OpenWeather

https://github.com/josecastroleon/pimatic-weather/issues/13#issuecomment-89509907

**Comment by ErikCoen** [comment]
I applied OpenWeather. It is now working! Thanks.

2015-04-04 18:19 GMT+02:00 pimagical <notifications@github.com>:
