### ISSUE TITLE
[0.9.x] A uncaught exception occured: Error: spawn ./node_modules/pimatic/ppm.js ENOENT

### ISSUE THREAD

**Issue by Yves911** [pimatic/pimatic#923]
Hello,

Since i installed the last update of the 0.9 version (0.9.22) i get this error message:
```
11:59:47.306 2016-06-12 Sunday
11:59:54.806 [pimatic] Starting pimatic version 0.9.22
11:59:57.981 [pimatic] A uncaught exception occured: Error: spawn ./node_modules/pimatic/ppm.js ENOENT
11:59:57.981 [pimatic]>    at exports._errnoException (util.js:870:11)
11:59:57.981 [pimatic]>    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
11:59:57.981 [pimatic]>    at onErrorNT (internal/child_process.js:344:16)
11:59:57.981 [pimatic]>    at nextTickCallbackWith2Args (node.js:442:9)
11:59:57.981 [pimatic]>    at process._tickCallback (node.js:356:17)
11:59:57.981 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!
11:59:58.026 [pimatic] exiting...
```

Same error with 0.9.21, 0.9.20, 0.9.19 
```
12:15:41.001 [pimatic] Starting pimatic version 0.9.21
coffee-cache: compiling coffee-script file "config-schema.coffee"...Done
12:15:44.911 [pimatic] A uncaught exception occured: Error: spawn ./node_modules/pimatic/ppm.js ENOENT
12:15:44.911 [pimatic]>    at exports._errnoException (util.js:870:11)
12:15:44.911 [pimatic]>    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
12:15:44.911 [pimatic]>    at onErrorNT (internal/child_process.js:344:16)
12:15:44.911 [pimatic]>    at nextTickCallbackWith2Args (node.js:442:9)
12:15:44.911 [pimatic]>    at process._tickCallback (node.js:356:17)
12:15:44.911 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!
12:15:44.935 [pimatic] exiting...
```

Latest version working fine for me 0.9.18.
Cheers
Yves

**Comment by sweebee** [comment]
Same here

**Comment by mwittig** [comment]
Try to restart from the command line and the error should disappear, i.e. sudo service pimatic restart

**Comment by sweetpi** [comment]
Should be solved with 0.9.23.

#7c11a35bd7642f0532b5a9e810ad1ab53c579e52

**Comment by Yves911** [comment]
Confirmed to be fixed with 0.9.23.

**Comment by michbeck100** [comment]
The problem still exists when running the unit tests on a fresh checkout of the master branch. At least when i run this on my mac. It also fails on the travis builds of my pimatic fork.

**Comment by michbeck100** [comment]
After analyzing the problem is obvious. 
plugins.coffee:353
```
ppmBin = './node_modules/pimatic/ppm.js'
npm = spawn(ppmBin, args, {cwd: @modulesParentDir, env: npmEnv})
```
the path './node_modules/pimatic/ppm.js' doesn't exist for the tests.

**Comment by michbeck100** [comment]
What i don't get, is why the tests don't fail for https://travis-ci.org/pimatic/pimatic
